/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Artigos: typeof import('./src/components/artigos.vue')['default']
    Atuacao: typeof import('./src/components/atuacao.vue')['default']
    Contatos: typeof import('./src/components/contatos.vue')['default']
    Foot: typeof import('./src/components/foot.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/hero.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Local: typeof import('./src/components/local.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    Preloader: typeof import('./src/components/preloader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Servicos: typeof import('./src/components/servicos.vue')['default']
    SobreNos: typeof import('./src/components/SobreNos.vue')['default']
  }
}
